filt=0.3;
filtrobajo=0.3;
cti=1;
ctf=3000;
SamplePlotFreq = 4;
Spin=120;
[pos,vel,posPlot,quatPlot,gyrX,gyrY,gyrZ,accX,accY,accZ,acc,time,acc_magFilt,stationary,samplePeriod]=script2('Run_number_2231_Plot_and_Store_Rep_6.5.csv',1,filt,filtrobajo);
posPlot=posPlot(cti:ctf,:);
quatPlot=quatPlot(cti:ctf,:);
SixDofAnimation(posPlot, quatern2rotMat(quatPlot), ...
                'SamplePlotFreq', SamplePlotFreq, 'Trail', 'All', ...
                'Position', [9 39 1280 768], 'View', [(100:(Spin/(length(posPlot)-1)):(100+Spin))', 10*ones(length(posPlot), 1)], ...
                'AxisLength', 0.1, 'ShowArrowHead', false, ...
                'Xlabel', 'X (m)', 'Ylabel', 'Y (m)', 'Zlabel', 'Z (m)', 'ShowLegend', false, ...
                'CreateAVI', false, 'AVIfileNameEnum', false, 'AVIfps', ((1/samplePeriod) / SamplePlotFreq));
